AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'db/schema.rb'
    # - 'config/**/*'
    # - 'script/**/*'
# Style/Documentation:
#   Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 5
Style/ClassAndModuleChildren:
  Enabled: false
